### ISSUE TITLE
sofaboot发布成bolt协议，端口冲突提示太诡异

### ISSUE THREAD

**Issue by qinliang373** [sofastack/sofa-rpc-boot-projects#190]
sofaboot发布成bolt协议，端口冲突提示太诡异
===================================
### Describe the bug
[2019-05-28 15:24:37]-[WARN]-[173]-[main]-[org.apache.catalina.loader.WebappClassLoaderBase.log]--[,] -The web application [ROOT] appears to have started a thread named [lettuce-eventExecutorLoop-1-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
 io.netty.util.concurrent.SingleThreadEventExecutor.takeTask(SingleThreadEventExecutor.java:251)
 io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:64)
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:748)
[2019-05-28 15:24:37]-[ERROR]-[858]-[main]-[org.springframework.boot.SpringApplication.reportFailure]--[,] -Application run failed
com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: Failed to start bolt server, see more detail from bolt log.
	at com.alipay.sofa.rpc.server.bolt.BoltServer.start(BoltServer.java:121) ~[sofa-rpc-all-5.5.1.jar:5.5.1]
	at com.alipay.sofa.rpc.boot.container.ServerConfigContainer.startServers(ServerConfigContainer.java:86) ~[rpc-sofa-boot-core-6.0.1.jar:6.0.1]
	at com.alipay.sofa.rpc.boot.context.SofaBootRpcStartListener.onApplicationEvent(SofaBootRpcStartListener.java:73) ~[rpc-sofa-boot-core-6.0.1.jar:6.0.1]
	at com.alipay.sofa.rpc.boot.context.SofaBootRpcStartListener.onApplicationEvent(SofaBootRpcStartListener.java:41) ~[rpc-sofa-boot-core-6.0.1.jar:6.0.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.alipay.sofa.rpc.boot.context.ApplicationContextRefreshedListener.onApplicationEvent(ApplicationContextRefreshedListener.java:39) ~[rpc-sofa-boot-core-6.0.1.jar:6.0.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.jsmfbank.sse.system.SofabootSystemServiceApplication.main(SofabootSystemServiceApplication.java:25) [classes/:?]
[2019-05-28 15:24:37]-[INFO]-[208]-[main]-[org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.shutdown]--[,] -Shutting down ExecutorService 'applicationTaskExecutor'
[2019-05-28 15:24:37]-[INFO]-[1885]-[main]-[com.alibaba.druid.pool.DruidDataSource.close]--[,] -{dataSource-1} closing ...
[2019-05-28 15:24:37]-[INFO]-[1955]-[main]-[com.alibaba.druid.pool.DruidDataSource.close]--[,] -{dataSource-1} closed
Disconnected from the target VM, address: '127.0.0.1:55586', transport: 'socket'

### Environment

- Starter version:
3.1.3
- JVM version (e.g. `java -version`):
 jdk1.8
- OS version (e.g. `uname -a`):
windows10
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
```
[2019-05-28 15:24:37]-[ERROR]-[858]-[main]-[org.springframework.boot.SpringApplication.reportFailure]--[,] -Application run failed
com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: Failed to start bolt server, see more detail from bolt log.
at com.alipay.sofa.rpc.server.bolt.BoltServer.start(BoltServer.java:121) ~[sofa-rpc-all-5.5.1.jar:5.5.1]

```

you can see logs/bolt/common-error.log

**Comment by qinliang373** [comment]
@leizhiyuan，建议像这类端口占用的问题最好能在启动时在控制台也有提示，目前看控制层给出的提示以为是内存不足“has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:”。在弱弱的问下bolt协议随机端口号是多少?
